# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
